/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminDefinicoesDePontosRouteImport } from './routes/admin/definicoes-de-pontos'
import { Route as AdminPontosDeCreditoRouteImport } from './routes/admin/pontos-de-credito'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDefinicoesDePontosRoute = AdminDefinicoesDePontosRouteImport.update({
  id: '/admin/definicoes-de-pontos',
  path: '/admin/definicoes-de-pontos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPontosDeCreditoRoute = AdminPontosDeCreditoRouteImport.update({
  id: '/admin/pontos-de-credito',
  path: '/admin/pontos-de-credito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/definicoes-de-pontos': typeof AdminDefinicoesDePontosRoute
  '/admin/pontos-de-credito': typeof AdminPontosDeCreditoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/definicoes-de-pontos': typeof AdminDefinicoesDePontosRoute
  '/admin/pontos-de-credito': typeof AdminPontosDeCreditoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/definicoes-de-pontos': typeof AdminDefinicoesDePontosRoute
  '/admin/pontos-de-credito': typeof AdminPontosDeCreditoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/definicoes-de-pontos'
    | '/admin/pontos-de-credito'
    | '/admin/usuarios'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/definicoes-de-pontos'
    | '/admin/pontos-de-credito'
    | '/admin/usuarios'
    | '/jobs/$jobId'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/definicoes-de-pontos'
    | '/admin/pontos-de-credito'
    | '/admin/usuarios'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminDefinicoesDePontosRoute: typeof AdminDefinicoesDePontosRoute
  AdminPontosDeCreditoRoute: typeof AdminPontosDeCreditoRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/definicoes-de-pontos': {
      id: '/admin/definicoes-de-pontos'
      path: '/admin/definicoes-de-pontos'
      fullPath: '/admin/definicoes-de-pontos'
      preLoaderRoute: typeof AdminDefinicoesDePontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pontos-de-credito': {
      id: '/admin/pontos-de-credito'
      path: '/admin/pontos-de-credito'
      fullPath: '/admin/pontos-de-credito'
      preLoaderRoute: typeof AdminPontosDeCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminDefinicoesDePontosRoute: AdminDefinicoesDePontosRoute,
  AdminPontosDeCreditoRoute: AdminPontosDeCreditoRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
